### ISSUE TITLE
Generated queries objects with fragments not works

### ISSUE THREAD

**Issue by Sparow199** [Sparow199/apollo-client-maven-plugin#3]

**Comment by kodayashi** [comment]
Hey @Sparow199 - I'm having this issue as well. Were you able to work around it using fragments?

**Comment by Sparow199** [comment]
Hi, have you tried with le latest version of the plugin? It's emmbed the
latest version of Apollo compiler. I think that it could be interesting to
try to generate the same queries with Gradle and compare the results.

**Comment by kodayashi** [comment]
Hi @Sparow199 - I'm using 1.3.0 for this plugin and 1.0.0 for the apollo dependency per the docs in this repo. I believe those are the latest.

**Comment by Sparow199** [comment]
Yes, they are the latest, there is a bug, but it's not easy to debug. I
have to look deeply to Gradle plugin.
