### ISSUE TITLE
Automatically run introspection query and build schema.json

### ISSUE THREAD

**Issue by kodayashi** [Sparow199/apollo-client-maven-plugin#5]
I wonder if it would be possible to automatically run the introspection query against a given graphql endpoint prior to building the java apollo client. I believe the apollo cli can download the schema with something like `apollo schema:download OUTPUT`.

Is there anything limiting the ability to do this? Re-downloading the results of an introspection query and checking it in frequently as a manual process would be a nice workflow to automate.

**Comment by kodayashi** [comment]
Yes I've confirmed the apollo cli can do this with:

```
schema:download schema.json --endpoint=https://my.appollo.server/graphql --header="Authorization: Bearer <my_jwt>"
```

The only difference is that the schema.json file required by this plugin needs to be wrapped with:

```json
{
  "data": {
    <response_from_apollo_cli>
  }
}
```

Would it be possible to expose a few plugin options so that this file can be dropped directly into the project at build time?

**Comment by kodayashi** [comment]
Actually this plugin can handle the generated (i.e. not wrapped with data: {}) json just fine. So would just be a matter of running the CLI to download the schema with a few optional params in the plugin I think (e.g. the endpoint, any headers, etc.)

**Comment by kodayashi** [comment]
Hi @Sparow199 - I forked this project and added two options to autogenerate the schema from an introspection query. Want me to submit a PR? You could merge it into this project if you like what you see. Let me know, thanks for publishing this updated fork it's been super helpful for us!

**Comment by Sparow199** [comment]
Hi,
Make a PR and will review it together.
Moncef

**Comment by kodayashi** [comment]
Done!

**Comment by Sparow199** [comment]
I'll merge it tomorrow and make a new release.
Thanks for the contribution.
Moncef
