### ISSUE TITLE
basePackage configuration is missing on plugin.xml parameters

### ISSUE THREAD

**Issue by leCandas** [Sparow199/apollo-client-maven-plugin#9]
basePackage configuration parameter is missing on plugin.xml parameters thus, IntelliJ IDEA is complaining.

**Comment by Sparow199** [comment]
Hi @leCandas,
It's already fixed in the **[develop](https://github.com/Sparow199/apollo-client-maven-plugin/blob/develop/apollo-client-maven-plugin-tests/pom.xml)** branch, i'll make a release ASAP. I'm working on multiples schema support and it's little more complicated.

**Comment by bonobonohu** [comment]
(it's still red in IntelliJ. :-( )

**Comment by Sparow199** [comment]
Hello, basePackage was removed, you have to use rootPackageName and
schemaPackageName to setup subpackage of custom types and fragments.

**Comment by Sparow199** [comment]
You have to update to v2.1.0 and all will be fine 👍

**Comment by bonobonohu** [comment]
thank you!
